lk-geimfari/mimesis

church/data/en_us/gender

Because some people are super sensitive.

/triggered

---

README.md

Update Readme typpo

---

church/data/pt-br/quotes

Minor corrections such as punctuation, and grammar.

Minor corrections to Quotes

---

church/utils.py

Remove some remnants leftover from the previous merge.

Remove remnants from #29

---

docs/guide.rst

Updated docs/guide.rst

---

docs/index.rst

From what I can tell this is all that needs to be changed due to the rename (#51).

Fix up name in index.rst

---

docs/guide.html
docs/guide.rst

Not sure if you wanted this, but I saw issue #51 so I decided to edit it.

Change 'church' in the example pages to 'elizabeth'

---

README.md

#79 Expand comparison section

---

elizabeth/core/elizabeth.py
tests/test_data/test_personal.py

Added support for American Express credit cards and error handling for unimplemented types.
Updated code to calculate Lunh Algorithm checksums, which will enable credit card numbers to pass validation. (See https://en.wikipedia.org/wiki/Luhn_algorithm)

Creditcards

---

elizabeth/core/elizabeth.py

expose keyword arguments
move setting of founded variable so it is not set when not needed

refactor copyright

---

README.md

reorganize and update README

---

elizabeth/core/elizabeth.py
elizabeth/core/interdata/__init__.py
elizabeth/core/interdata/code.py
elizabeth/utils.py
tests/test_utils.py

- Relocated Luhn algorithm checksum function to utils so it can be used elsewhere.
- Refactored imei method to generate IMEIs for actual device models, with valid checksums. 
- Type Allocation / Final Assembly codes from https://en.wikipedia.org/wiki/Type_Allocation_Code
- Can be checked against third-party services such as https://swappa.com/esn and will show actual device info
- Updated tests for utils

IMEI Improvements

---

docs/index.rst

add back search box removed in prior commit

---

elizabeth/core/elizabeth.py
tests/test_data/test_personal.py

Store generated object field value to generate depended fields - example for Personality.age
https://github.com/lk-geimfari/elizabeth/issues/107
With test coverage

Store generated object field value to generate depended fields - example for Personality.age

---

CONTRIBUTING.md
elizabeth/core/elizabeth.py
elizabeth/utils.py
tests/test_data/_patterns.py
tests/test_data/test_address.py
tests/test_data/test_business.py
tests/test_data/test_code.py
tests/test_data/test_datetime.py
tests/test_data/test_food.py
tests/test_data/test_personal.py
tests/test_data/test_sciense.py
tests/test_data/test_structured.py
tests/test_data/test_text.py

#112
added __str__ to providers with test cases.
I also fixed the warning messages coming from **assertEquals**
> elizabeth/tests/test_data/test_personal.py:142: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(int(size), 512)

add __str__ to providers with locale

---

tests/test_data/test_internet.py

Fix regexp in tests/test_internet.py

---

tests/test_data/test_datetime.py

@lk-geimfari this will fail to pass tests until ko and jp locales are fixed per issue #131

improve time test/increase coverage

---

elizabeth/utils.py
tests/test_utils.py

@lk-geimfari as requested in #133

clean up downloaded image after test

---

docs/api.rst

add structured provider to API documentation

---

CONTRIBUTORS.md
elizabeth/core/providers.py
tests/test_data/test_business.py
tests/test_generic.py

Update generic class

---

.gitignore
CONTRIBUTING.md
elizabeth/core/providers.py

Changes:
1. Removes `__str__` method from every class
2. It is now handled by new `BaseProvider` class
3. Adds `.gitignore` as industry-standard
I guess, it would also be a good idea to separate providers by different modules. Since it is almost 2k LOC. Really hard to read.

Adds base class for all provides

---

PYPI_README.rst

add missing quotation mark in document.
find this issues while I'm following the document.

add missing quotation mark

---

elizabeth/builtins/en.py
elizabeth/builtins/ru.py
elizabeth/providers/date.py
elizabeth/providers/generic.py
elizabeth/providers/internet.py
elizabeth/providers/personal.py
elizabeth/providers/structured.py
tests/conftest.py

fix tests issue #178

---

mimesis/providers/__init__.py
mimesis/providers/generic.py

All the tests were passed. Local build works well.

Completed TODO: Resolve importing errors and use importing format as above.

---

docs/guide.rst

indentation fixed in example python code of "Path"

indentation fixed

---

docs/api.rst
docs/index.rst
mimesis/providers/address.py
mimesis/providers/cryptographic.py
mimesis/providers/file.py
mimesis/providers/internet.py
mimesis/providers/path.py
mimesis/providers/personal.py
mimesis/providers/structured.py

- updated source file `api.rst` for documentation
- resolved WARNINGs `make html` command
So now we can exec. `make html` and get a relevant documentation.

Fix for generate new documentation

---

mimesis/helpers.py

PR for [#250](https://github.com/lk-geimfari/mimesis/issues/250)
Removed super class initialization in random class.

Fixed custom Random class in helpers.py

---

mimesis/providers/cryptographic.py
tests/test_data/test_cryptographic.py

Implemented salt() method for generating not safe salt for testing.

Added salt() to Cryptographic()

---

mimesis/exceptions.py
mimesis/schema.py
mimesis/utils.py

Just some basic updates I found while reviewing the code base.
By the way, this seems like a cool project!

Some basic code/comment updates

---

mimesis/builtins/base.py
mimesis/builtins/ru.py
mimesis/builtins/uk.py
mimesis/helpers.py
mimesis/providers/__init__.py
mimesis/providers/address.py
mimesis/providers/base.py
mimesis/providers/business.py
mimesis/providers/clothing.py
mimesis/providers/code.py
mimesis/providers/cryptographic.py
mimesis/providers/date.py
mimesis/providers/development.py
mimesis/providers/file.py
mimesis/providers/food.py
mimesis/providers/games.py
mimesis/providers/generic.py
mimesis/providers/hardware.py
mimesis/providers/internet.py
mimesis/providers/numbers.py
mimesis/providers/path.py
mimesis/providers/payment.py
mimesis/providers/personal.py
mimesis/providers/science.py
mimesis/providers/structured.py
mimesis/providers/text.py
mimesis/providers/transport.py
mimesis/providers/units.py
tests/test_data/test_base.py

* Redesign Base providers. Now for date providers we have BaseDataProvider and super class BaseProvider
* BaseSpecProvider have superclass BaseProvider
* BaseProvider contains seed and random object

Fixed spec provider seed issues

---

mimesis/builtins/ru.py
tests/test_builtins/ru/test_russia_spec.py

Add OGRN and BIC data generators for RussiaSpecProvider #318

Add some data generators for RussiaSpecProvider

---

mimesis/__init__.py
tests/test_generic.py
tests/test_providers/test_address.py
tests/test_providers/test_base.py
tests/test_providers/test_business.py
tests/test_providers/test_clothing_sizes.py
tests/test_providers/test_code.py
tests/test_providers/test_cryptographic.py
tests/test_providers/test_datetime.py
tests/test_providers/test_development.py
tests/test_providers/test_file.py
tests/test_providers/test_food.py
tests/test_providers/test_games.py
tests/test_providers/test_hardware.py
tests/test_providers/test_internet.py
tests/test_providers/test_numbers.py
tests/test_providers/test_path.py
tests/test_providers/test_payment.py
tests/test_providers/test_personal.py
tests/test_providers/test_science.py
tests/test_providers/test_structured.py
tests/test_providers/test_text.py
tests/test_providers/test_transport.py
tests/test_providers/test_unit_system.py

What was be done:
Why:
It was too hard to maintain the previous tests.

Updated tests

---

CHANGELOG.md
docs/comparison.rst
mimesis/helpers.py
mimesis/providers/address.py
mimesis/providers/business.py
mimesis/providers/hardware.py
mimesis/providers/numbers.py
tests/test_helpers.py
tests/test_providers/test_address.py

- Updated custom method `Random.unofirm`
- Added support of parameter `dms` for coordinates.
```python
from mimesis import Address
ad = Address(seed=0xf)
print(ad.coordinates())
ad = Address(seed=0xf)
print(ad.coordinates(dms=True))
```
Output:
```
{'longitude': 167.487171, 'latitude': -87.902155}
{'longitude': '167º29\'13.816"E', 'latitude': '87º54\'7.758"S'}
```

Added dms support for coordinates

---

CHANGELOG.rst
mimesis/providers/base.py
mimesis/schema.py
mimesis/utils.py
tests/test_generic.py
tests/test_providers/patterns.py
tests/test_providers/test_address.py
tests/test_providers/test_base.py
tests/test_providers/test_business.py
tests/test_providers/test_clothing_size.py
tests/test_providers/test_code.py
tests/test_providers/test_cryptographic.py
tests/test_providers/test_datetime.py
tests/test_providers/test_development.py
tests/test_providers/test_file.py
tests/test_providers/test_food.py
tests/test_providers/test_games.py
tests/test_providers/test_hardware.py
tests/test_providers/test_internet.py
tests/test_providers/test_numbers.py
tests/test_providers/test_path.py
tests/test_providers/test_payment.py
tests/test_providers/test_person.py
tests/test_providers/test_science.py
tests/test_providers/test_structure.py
tests/test_providers/test_text.py
tests/test_providers/test_transport.py
tests/test_providers/test_unit_system.py
tests/test_schema.py
tests/test_utils.py

Removed useless internal function

---

mimesis/data/locale_template/README.md

There is some inaccuracy in `locale_template`.

Сorrection of inaccuracy

---

tests/test_providers/test_development.py

[tests] Fix a broken test related to version control systems

---

mimesis/providers/business.py
mimesis/providers/cryptographic.py

Fixes flake8 issues, closes #434

---

mimesis/decorators.py
tests/test_decorators.py

prevent ROMANIZATION_DICT from mutating

---

CONTRIBUTORS.rst
mimesis/utils.py
tests/test_utils.py

I have fixed function `download_image`. Also fixed if `save_path` without trailing slash.

Fixed issue with names on downloading images

---

appveyor.yml

Removed Python 3.5 from AppVeyor and added Python 3.7

---

.gitignore
.travis.yml
appveyor.yml
setup.cfg

Added OSX support

---

Pipfile
Pipfile.lock

Link: https://github.com/sobolevn/flake8-type-annotations

Adds flake8-type-annotations to lint types

---

mimesis/enums.py

An enhancement was made within "Change examples to be doctests #436" issue.
It decreases an amount of bugs `DocTestFailure`.

An enhancement in enums provider doctest

---

CONTRIBUTING.rst
CONTRIBUTORS.rst

Closes #555

---

CHANGELOG.rst
CONTRIBUTORS.rst
Pipfile.lock
docs/api.rst
docs/quickstart.rst
mimesis/builtins/pl.py
tests/test_builtins/pl/test_poland_spec.py

* Added `PolandSpecProvider`
* Added PESEL generation for `PolandSpecProvider`
* Added NIP generation for `PolandSpecProvider`
* Added REGON generation for `PolandSpecProvider`
* Added test_case for `PolandSpecProvider.pesel`
* Added test_case for `PolandSpecProvider.nip`
* Added test_case for `PolandSpecProvider.regon`
* Updated CHANGELOG.rst
* Updated CONTRIBUTORS.rst
* Updated docs
- [x ] I have read [contributing guidelines](https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTING.rst)
- [ x] I'm sure that the cat did not jump to the keyboard and did not unrelated changes in this pull request
- [ x] I have created at least one test case for the changes I have made
- [ x] I have updated the documentation for the changes I have made
- [ x] I have added myself to the …

feature: Added builtin provider for Poland.

---

CONTRIBUTORS.rst
mimesis/data/fr/address.json
mimesis/data/fr/food.json
mimesis/data/fr/person.json

Modified French person.json

---

mimesis/providers/file.py
mimesis/providers/payment.py

@lk-geimfari This PR updates several regular expression string literals to be `r'strings'`. This prevents an invalid escape sequence deprecation warning on newer versions of Python 3:
```
.venv/lib/python3.7/site-packages/mimesis/providers/file.py:35
/.../.venv/lib/python3.7/site-packages/mimesis/providers/file.py:35: DeprecationWarning: invalid escape sequence \s
return re.sub('\s+', replacer, string.strip())
.venv/lib/python3.7/site-packages/mimesis/providers/payment.py:101
/.../.venv/lib/python3.7/site-packages/mimesis/providers/payment.py:101: DeprecationWarning: invalid escape sequence \d
regex = re.compile('(\d{4})(\d{4})(\d{4})(\d{4})')
.venv/lib/python3.7/site-packages/mimesis/providers/payment.py:116
/.../.venv/lib/python3.7/site-packages/mimesis/providers/payment.py:116: …
```

Annotate regular expressions as r'strings'.

---

.github/ISSUE_TEMPLATE/Custom.md

Removes Custom issue template

---

CONTRIBUTORS.rst
mimesis/data/en-au/address.json

Add missing state for Australia

---

CONTRIBUTORS.rst
docs/getting_started.rst

Added docs for installing mimesis in Jupyter notebook - Issue #722

---

.travis.yml
mimesis/providers/internet.py

Add Python 3.8 support to Travis CI

---

.travis.yml
Makefile

Change py.test to pytest

---

CONTRIBUTORS.rst
mimesis/data/cs/datetime.json

Fix CS Datetime formats

---

docs/conf.py
mimesis/builtins/ru.py
mimesis/providers/address.py
mimesis/providers/choice.py
mimesis/providers/internet.py
mimesis/providers/person.py

Fix codefactor issues

---

tests/test_providers/test_numbers.py

Fix formatting of complex numbers in test

---

README.rst
mimesis/schema.py
mimesis/typing.py
setup.cfg
tests/test_schema.py

Fix typing issue

---

.github/labeler.yml
.github/workflows/labeler.yml
CONTRIBUTORS.rst

Add PR labeler

---

tests/test_providers/patterns.py
tests/test_providers/test_internet.py

Improve test coverage of stock_image()

---

.github/workflows/test.yml

Uncomment codecov

---

.github/workflows/publish.yml
.github/workflows/test.yml

I forgot to add `pull_request` to trigger workflow.. we only had on `push`. I see [here](https://github.com/lk-geimfari/mimesis/runs/1506865699?check_suite_focus=true) that tests was failing on windows so I added `--user` to pip install commands. 
Python 3.9 is failing on **mypy** issues:
```shell
mimesis/builtins/en.py:72: error: syntax error in type comment
```

Fix CI issues

---

mimesis/builtins/en.py
mimesis/random.py
tests/test_random.py

Fix mypy issues

---

.github/FUNDING.yml
CHANGELOG.rst
CONTRIBUTORS.rst
mimesis/builtins/da.py
tests/test_builtins/da/test_denmark_spec.py

This PR reworks CPR generation within the DenmarkSpecProvider, as discussed on #1050.
Closes #1050.

Rework CPR generation

---

README.rst

Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Correct GHA badge in README

---

mimesis/builtins/da.py
mimesis/builtins/en.py
mimesis/builtins/it.py
mimesis/builtins/nl.py
mimesis/builtins/pl.py
mimesis/builtins/pt_br.py
mimesis/builtins/ru.py
mimesis/builtins/uk.py
mimesis/providers/base.py
mimesis/providers/generic.py
mimesis/schema.py
mimesis/typing.py

Makes the following changes:
- Added `float` to the `Union` for `Seed`.
- Added `None` to the `Union` for `Seed`.
- Replaced `Optional[Seed]` with `Seed` everywhere.
See the following links for details:
- https://bugs.python.org/issue32554
- https://github.com/python/cpython/pull/15382
- https://docs.python.org/3.9/library/random.html#random.seed
Currently `typeshed` is still using `Any`.
- [n/a] I have created at least one test case for the changes I have made

Fix types for Seed.

---

CHANGELOG.rst
mimesis/providers/address.py

Before:
```
In [1]: from mimesis.providers import Address
...: f = Address._dd_to_dms
In [2]: %timeit f(57.12345, "lt")
1.18 µs ± 2.07 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
After:
```
In [2]: %timeit f(57.12345, "lt")
760 ns ± 2.61 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

Optimized ``Address._dd_to_dms()``.

---

mimesis/builtins/pl.py
mimesis/builtins/pt_br.py
mimesis/builtins/ru.py
mimesis/exceptions.py

Interally, `str.join()` first converts to a list, so it is preferable to use a list comprehension instead of a generator. In addition, it seems to be faster to use `map(str, ...)` rather than the comprehension `[str(x) for x in ...]`:
In [1]: %%timeit r = range(128)
...: "".join(str(x) for x in r)
11.5 µs ± 246 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [2]: %%timeit r = range(128)
...: "".join([str(x) for x in r])
10 µs ± 62.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [3]: %%timeit r = range(128)
...: "".join(map(str, r))
8.49 µs ± 118 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

Updated to use `map()` with `str.join()`.

---

mimesis/builtins/ru.py

Removed unnecessary calls to `str.format()`.

---

CHANGELOG.rst
mimesis/providers/payment.py
mimesis/providers/person.py
mimesis/random.py

Available since Python 3.6, `random.choices()` is significantly faster when generating a random string:
In [1]: import random, string
In [2]: characters = string.ascii_letters + string.digits
In [3]: %timeit "".join(random.choice(characters) for _ in range(128))
29.3 µs ± 87.2 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [4]: %timeit "".join(random.choices(characters, k=128))
7.92 µs ± 186 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Note that this is backward incompatible with respect to reproducibility because the two methods use different algorithms.
See https://docs.python.org/3/library/random.html#random.choices
Despite this, because of the improvement in performance - one of the stated goals of this package, this seems like a reasonable trade off.

Updated to use `random.choices()` for random strings.

---

CHANGELOG.rst
mimesis/providers/development.py
tests/test_providers/test_development.py

Updated to simplify the implementation and avoid use of `str.format()`.
In addition, support pre-release modifiers with CalVer. See https://calver.org/ for details.

Optimized ``Development.version()``, support pre-release for CalVer.

---

mimesis/builtins/da.py
mimesis/builtins/pl.py
mimesis/builtins/ru.py
mimesis/providers/base.py
mimesis/providers/date.py
mimesis/providers/file.py
mimesis/providers/generic.py
mimesis/providers/hardware.py
mimesis/providers/internet.py
mimesis/providers/payment.py
mimesis/providers/person.py
mimesis/providers/transport.py
mimesis/schema.py
tests/test_providers/test_numeric.py

Using f-strings is generally much faster. In addition, simplify formatting of dates - format strings support the date and time format strings, e.g. %Y for four-digit year, etc.

Updated to use f-strings over `str.format()`.

---

mimesis/providers/text.py

Fix typo in docstring for `Text.words()`.

---

mimesis/providers/text.py

Follow up to 27f144f9cb9263f1d4384be77e1f9b3c837190e9.
See also #1158.
I'm interested to see if this also resolves the problems with flaky
tests when calling either of the `Internet.query_string()` and
`Internet.query_parameters()` methods.
The former calls the latter and I suspect that the issue is caused by
the first call to `self.text.words()` returning duplicates which results
in overwriting a key in the dictionary that is constructed. As such, the
length of parameters is less than that requested.
I'm not sure if, by using `random.choices()` instead of many calls to
`random.choice()` in `Text.words()`, we'll have less chance of duplicate
values being chosen, but it seems prudent from a performance perspective
anyway.

Updated to use `random.choices()` in more places.

---

mimesis/providers/transport.py

Replaced card with car in the method docstring
- [x ] I have read [contributing guidelines](https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTING.rst)
- [x ] I'm sure that I did not unrelated changes in this pull request

Fix typo in Transport manufacturer Docstring

---

mimesis/providers/address.py
tests/test_providers/test_address.py

- Closes #1248
I copied the relevant changes from #1114 and credited the original author in the commit. Please let me know if you want any other changes.

Add allow_random param in country method of Address provider

---

mimesis/providers/hardware.py
tests/test_providers/test_hardware.py

tweak `AUTO_MANUFACTURERS` to `MANUFACTURERS`

fix: hardware manufacturers

---

mimesis/providers/base.py
mimesis/providers/development.py
mimesis/providers/internet.py
mimesis/providers/payment.py
tests/test_providers/test_base.py
tests/test_providers/test_internet.py

The providers now accept `random` argument to make it easier to reseed all the providers which are used in other providers .
See https://github.com/lk-geimfari/mimesis/issues/1313 for more details.

Fix seeding issues

---

CONTRIBUTORS.rst
tests/test_providers/test_datetime.py
tests/test_providers/test_hardware.py
tests/test_providers/test_internet.py
tests/test_providers/test_person.py

Hello, first-time submitting PR here.
This PR improves the readability of the assert statements in some of the unit tests. These changes improve code quality (avoid test smells) by:
- Making the assert statements more readable and consist with other asserts in the same test file, e.g., x <= var <= y. 
- Simplifying code management. For example, instead of simply saying "https", use the parameter name(URLScheme.HTTPS.value) so that developers could only update the value in one place.
- Using more precise assert statements to restrict the assert rules.
Happy to update more related issues in the test code if needed :)

Assert statements refactoring

---

CHANGELOG.rst
docs/_static/css/custom.css
docs/schema.rst
mimesis/__init__.py
mimesis/exceptions.py
mimesis/schema.py
pyproject.toml
tests/test_keys.py
tests/test_schema.py

Custom field handlers

---

mimesis/datasets/hr/address.json

Update address.json for hr locale

---

README.md

Fixed a broken link I ran into.
Thanks for the awesome library!

Fix broken readme link
