elizabeth/core/elizabeth.py
tests/test_data/test_code.py

The CPF and CNPJ are codes use for identifying brazilian persons and
companies, since it requires some calculation it cannot be generated
with the custom code
Signed-off-by: Alessandro Martini <alessandrofmartini@gmail.com>

Added CPF and CNPJ to the Code class

---

elizabeth/core/elizabeth.py
tests/test_generic.py

Issue #74
`add_provider()` on Generic adds an instance of the provider class, so a new provider class such as `my_generic.add_provider(SampleProvider)` will let you call `my_generic.SampleProvider.method()` afterwards.
I used the class name to set the attribute, but it could definitely be changed to look for a key variable in the new provider to set the attribute within the generic provider.
Raises TypeError if a class type is not passed.

Added 'add_provider' to generic provider

---

elizabeth/core/elizabeth.py
tests/test_generic.py

Added the ability to set the provider name via a meta subclass. If the subclass isn't available the name will be set using the standard way (`cls.__name__.lower()`).
Modified the test to use an alternate name to test the functionality.

Added check for meta class to set provider name

---

docs/guide.rst

Person.occupation() method was referred to as Person.profession() in examples.

fixed issue with wrong method name in documentation

---

elizabeth/builtins/specific_providers.py
tests/test_builtins.py

I removed the geographical area codes because according to [this](https://www.ssa.gov/employer/randomization.html) they are no longer relevant. Let me know if you'd like anything changed. Thanks!

Add returning a random SSN to USA provider

---

elizabeth/data/pl/address.json

The Polish continent names were in accusative case for no good reason.
Make them nominative instead.

Fix Polish continent names

---

elizabeth/data/pl/address.json

I don't what what *axis.* is supposed to stand for, but we certainly don't use it in Polish addresses.

Remove bogus "axis." as Polish address component

---

PROVIDERS.md

I'm not sure if 'all at one' is deliberate, but just in case!

fix typo in Generic Provider

---

docs/index.rst
docs/part_1.rst
docs/part_2.rst
docs/providers.rst
mimesis/providers/internet.py
mimesis/providers/personal.py

Different warnings were fixed for the sphinx documentations. They were
mostly underline oder overline too shorts as well as missing indedations
either in the documentation files or in the docstings
The only one missing is 'Duplicate explicit target name: "here".' in the
index.rst file. I was unchanged since here refences two different
documents.

Fix sphinx warnings

---

mimesis/data/nl/address.json

Changed address format to {st_name} {st_num} for locale nl.

#294 - switch address format for nl

---

mimesis/builtins/__init__.py
mimesis/builtins/nl.py
tests/test_builtins/nl/test_nl_spec.py

Added the NLSpecProvider for the locale nl to generate a _burgerservicenummer_ or BSN. This is the Dutch equivalent of a social security number.

builtin specprovider for locale nl

---

CHANGELOG.md
mimesis/schema.py
setup.cfg
tests/test_schema.py

Some data providers have methods with the same name (`Personal.title` and `Text.title`) and previous version of `schema.Field` always returns a result of the method `title()` of provider `Personal()`:
```python
>>> from mimesis.schema import Field
>>> _ = Field('en')
>>> _('title')
'Mr.'
```
Now we can explicitly define that the method belongs to data-provider ``cls``:
```python
>>> _('title', cls='text')
'She spent her earliest years reading classic literature.'
>>> _('title', cls='personal')
'Mrs.'
```
---
In addition, an explicit definition significantly increases the speed of work:
**The result on defined `cls`**:
```python
_ = Field('en')
description = (
lambda: {
'id': _('cryptographic.uuid'),
'name': _('text.word'),
'version': _('development.version', pre_release=True), …
```

Added explicit definition of provider

---

docs/quickstart.rst
mimesis/providers/person.py
tests/test_providers/test_person.py

The correct name of the class is BrazilSpecProvider
Variable name 'children' proposed in place of childs

Documentaion fix and a variable name update

---

docs/quickstart.rst

Replace  "lower registers" with "lowercase letters" + a typo

Just language clarity

---

CONTRIBUTORS.rst
mimesis/providers/internet.py
tests/test_providers/test_internet.py

Previous url returns not relevance image.
before:
https://source.unsplash.com/category/sea/1900x1080
now:
https://source.unsplash.com/1900x1080/?sea
in addition, category (or search keyword) can be coma separated list, like so https://source.unsplash.com/1900x1080/?sea,sun
Unsplash reference https://source.unsplash.com/

change Unsplash image url with more relevance results

---

Pipfile.lock
appveyor.yml
mimesis/helpers.py
mimesis/providers/base.py
mimesis/providers/business.py
mimesis/providers/cryptographic.py
tests/test_helpers.py

What have I done?
1. I have made it easy to provide global seed for all providers at one place. For this purpose I am exposing `mimesis.helpers.random` instance
2. I have also changed how `seed` argument works. Now first call to the `reseed()` method creates an internal instance of `Random` to generate equal values for different instances of the same provider
3. I have also fixed `flake8-builtins` warnings 
Closes #470 
Closes #467
Related #469

Changes how internal random generator works

---

.gitignore

So with this PR `.gitignore` was extended with `.code-workspace`.

Add to .gitignore Visual Studio Code trash

---

.travis.yml

There is [bug](https://github.com/pypa/pipenv/issues/2924) with pipenv used with pip==18.1.
Because of that all Travis builds for python3.7 are failing.
I added temporary workaround.

Fix pipenv with pip==18.1 bug

---

mimesis/choice.py
tests/test_choice.py

There was a possible bug involving how the `choice` module was handling the initial seed. This PR fixes it. Also improves coverage of the same module. Tests included.
Please let me know if it needs any change.

This fixes how choice uses random seed

---

mimesis/providers/payment.py

Noticed that generated Mastercard BIN numbers are different from documentation.
[Mastercard Rules](https://www.mastercard.us/content/dam/mccom/global/documents/mastercard-rules.pdf) - Page 73.

Mastercard BINs range corrected

---

CONTRIBUTORS.rst
mimesis/providers/person.py
tests/test_providers/patterns.py
tests/test_providers/test_person.py

- Closes #609 
Couple of things:
**1**. Assigned the hard coded values to ```MIN_DATE``` and ```MAX_DATE```. I will be able to use these while I implement #608.
**2**. I noticed that the unit test for ```Person.email()``` was asserting the returned value with a generic regular expression. I created patterns for each template. The unit test will now assert that the returned value of ```Person.email()``` matches the pattern for the template that was passed as a parameter.

Fix issue #609 and improve unit test for Person.username()

---

CHANGELOG.rst
CONTRIBUTORS.rst
mimesis/providers/generic.py

Seed is not passed to custom provider when add_provider is called, this PR fix this.

pass seed to custom provider

---

mimesis/data/int/path.py
mimesis/providers/path.py
tests/test_providers/test_path.py

- Closes #607
- Refs #607 
I've refactored the Path data provider using the [pathlib](https://docs.python.org/3/library/pathlib.html) library as suggested in #607.
In order to remove that strange loops over the `PLATFORMS` dictionary I have changed the internals of the `path.py` module: now the main keys are the platform strings (*linux*, *darwin*, *win32* and *win64*) and the only thing specified in the dictionary is the *home* path:
```
PLATFORMS = {
'linux': {
'home': '/home/',
},
'darwin': {
'home': '/home/',
},
'win32': {
'home': 'C:\\Users\\',
},
'win64': {
'home': 'C:\\Users\\',
},
}
```
I have introduced a private variable `_pathlib_home` that is a [PurePath](https://docs.python.org/3/library/pathlib.html?highlight=purepath#pathlib.PurePath) object …

Refactor Path data provider with pathlib

---

CHANGELOG.rst
docs/api.rst
mimesis/builtins/__init__.py
mimesis/builtins/da.py
tests/test_builtins/da/test_denmark_spec.py

I've added a _DenmarkSpecProvider_ for the _da_ locale so users can generate a _CPR-number_. This is the danish version of a social security number.

DenmarkSpecProvider added

---

CHANGELOG.rst
mimesis/random.py
tests/test_random.py

I have removed the function `multiple_choice()` from the random module. It wasn't used by any other function, but, anyway, I found its implementation useless because from Python >= 3.6 there is the [choices](https://docs.python.org/3/library/random.html#random.choices) function that does exactly the same thing.

Remove multiple_choice

---

CHANGELOG.rst
mimesis/providers/generic.py
tests/test_providers/test_generic.py

Format is:
- Closes #674 
- Refs #674 
Now the Generic provider comes with the builtin provider of the selected locale (if available). If no locale are specified, then it will have the default locale provider ('en').
Examples:
>>> g = Generic()
>>> g.usa_provider.personality()
'INFP'
>>> g = Generic(locale='ru')
>>> g.russia_provider.in()
'391922215031'
As I said in the referenced issue, I think that adding the builtin provider by default is the easiest thing to do. I think that adding more parameters such as `auto_add_builtin` or `builtin_custom_name` will bring unnecessary complexity to the API.

Generic dev

---

Pipfile.lock

Format is:
- Closes #759 
- Refs #759
I have manually updated the `mypy-extensions` entry to the 0.4.3 version in the `Pipfile.lock` in order to make the tests pass in Linux. 
The build still doesn't pass because of the Windows 10 environment with Python 3.7. I'm sorry but I'm not familiar with Windows so I can't reproduce it.

Bumped mypy-extensions to 0.4.3

---

.travis.yml

I believe the "Python 3.7" Windows build is currently failing because the underlying `choco` package was bumped to Python 3.9.x, leaving the `PATH` incorrect. Since 3.6 and 3.7 are the targets on other platforms, I have pinned the Windows choco package requirements accordingly.
This references the comments made on #759 and #760.
~I may need to force-push a few pull requests to verify Travis CI moves to passing (as I do not have branch commit access with you all upstream). I will post a comment when this is ready to merge.~
My first build attempt is a success. @lk-geimfari for when you get a chance, I'll update my other commit to build off this one as well so you can see it passing and get both changes merged. Thanks for the prompt replies yesterday.

Pin Windows CI packages for python3 to latest 3.6 and 3.7 releases

---

.travis.yml
CONTRIBUTORS.rst
mimesis/providers/base.py
mimesis/providers/choice.py

This brief patch resolves the deprecation warnings emitted by Python 3.6+ due to `import collections`.
I *suspect* this may be acceptable as-is, but if you desire Python 2.x backward compatibility (e.g. with a `try ... except ...` import) or unit tests, I can reformat the patch accordingly--though admittedly, unit testing that deprecation warnings are not emitted probably qualifies as pedantic.
Projects importing `mimesis` will notice the deprecation warning during runtime, as seen in this `pytest` output for a test that imported the `choice` provider:
```
tests/sample.py::SampleTest::test_sample
.tox/py38/lib/python3.8/site-packages/mimesis/providers/choice.py:62: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since …
```

Resolve Python 3.6+ deprecation warnings for collections.abc

---

CHANGELOG.rst
Pipfile.lock
mimesis/providers/internet.py
tests/test_providers/test_internet.py

I have added a new method to ensure the support of IP objects using `ipaddress` model from the standard library.
Usage:
```python
from mimesis import Internet
>>> net.ip_v4() # Also this method now support new argument — port_range
'158.184.192.44'
>>> net.ip_v4_object() # <-- This is a new feature
IPv4Address('113.69.6.167')
>>> net.ip_v6()
'8615:7b8d:4744:c9cf:18e4:16c:9bf2:7689'
>>> net.ip_v6_object() # <-- This is a new feature
IPv6Address('58f8:1d67:a62c:3b48:f1a5:16a6:14ea:2901')
```

Add support of IP objects for the Internet provider (Fix #761)

---

CHANGELOG.rst
mimesis/enums.py
mimesis/providers/numbers.py
tests/test_providers/test_generic.py
tests/test_providers/test_numbers.py

Version 4.0.0
-------------
**This release (4.0.0) contains some insignificant but breaking changes in API**
**Added**:
- Added method ``complexes()`` for provider ``Numbers()``
- Added method ``matrix`` for provider ``Numbers()``
- Added method ``integer`` for provider ``Numbers()``
- Added method ``float`` for provider ``Numbers()``
- Added method ``complex`` for provider ``Numbers()``
- Added method ``decimal`` for provider ``Numbers()``
**Updated**:
- The ``floats()`` function in the ``Numbers`` provider now accepts arguments about the range of the generated float numbers and the rounding used. By default, it generates a list of ``n`` float numbers instead of a list of 10^n elements.
**Removed**:
- Removed the ``rating()`` method from the ``Numbers`` provider. It can be replaced with …

Upgrade data provider "Numbers" (Fix #800)

---

CONTRIBUTING.rst
CONTRIBUTORS.rst
Makefile

Hey there. This is my first pull request for an open source project. :)
- Closes #468 
I've already described my ideas in my first draft in the issues thread. 
But what it boils down to:
Give the option to specify the --randomly-seed option from the Makefile to make easier use of this feature. 
I have updated the contributing guide to introduce the feature.

Add pytest-randomly seedsetting functionto Makefile

---

mimesis/random.py
tests/test_random.py

`random.Random.custom_code` raised `IndexError: bytearray index out of range` if `mask` contained characters beyond ASCII because the created `code` `bytearray` was shorter than the encoded `mask`.
This fixes the issue (and adds a test) that allows the whole Unicode in `mask` (still not in `char`/`digit` placeholders). In UTF-8 this is possible since characters beyond ASCII are encoded using bytes other than 32–126.

Fix unicode support in Random.custom_code

---

CONTRIBUTING.rst
mimesis/data/locale_template/README.md

- Travis tests against Python 3.8 too
- SUPPORTED_LOCALES reference moved to `mimesis/locales.py`
- Remove reference to adding a flag to README.md (did I miss anything?)

Update contributor's documentation

---

.github/workflows/test.yml
CHANGELOG.rst
CONTRIBUTING.rst
setup.py

Added Python 3.9 support in GitHub Actions and `setup.py`. Fix docs (and replace Travis with Github Actions).

add Python 3.9 support

---

mimesis/builtins/ru.py

Need a space between series and number in RU passport.

Update format for series_and_number

---

CONTRIBUTING.rst
CONTRIBUTORS.rst

- [n/a] I have created at least one test case for the changes I have made
The `Makefile` was removed in v5.0.0 and `CONTRIBUTING.rst` has outdated references to `make test` and `make type-check`,

Fixed references to `make` in `CONTRIBUTING.rst`.

---

CHANGELOG.rst
mimesis/shortcuts.py

Performance of the current implementation:
In [1]: from mimesis.locales import Locale
...: from mimesis.shortcuts import romanize
...: string = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя"
In [2]: %timeit romanize(string, locale=Locale.RU)
10.3 µs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
Making use of `str.maketrans()` and `str.translate()` avoids the need for the inclusion of ASCII characters in the translation table and improves the performance:
In [2]: %timeit romanize(string, locale=Locale.RU)
5.15 µs ± 74.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
It is also unnecessary to regenerate the translation table for every call to `romanize()`, so we can cache it for another boost:
In [2]: %timeit romanize(string, …

Updated `romanize()` to improve performance.

---

CHANGELOG.rst
mimesis/providers/generic.py
tests/test_providers/test_generic.py

Regression in 94eee4ebfd3c0bde76427e3b59fb65a5ac144595.
This ensures that the `random` instance on `Generic` itself is reseeded to allow reproducible use of standard random methods without using a subprovider. This also ensures that instances of `Generic` have isolated copies of the random number generator.
Closes #1150.

Fix reseeding of random generator on `Generic`.

---

CHANGELOG.rst
mimesis/providers/base.py
tests/test_providers/test_base.py

Originally a dedicated random instance was used for `BaseProvider` when it was changed in c44bd931a05b871783771af7152f1217dd8b8185. It should be noted that the random instance was not seeded when passing `None`, but this was in effect irrelevant because the default seed it `None` and the following:
```python
self.random = Random()
if seed is not None:
self.random.seed(seed)
```
Could have been written as the following and worked the same:
```python
self.random = Random(seed)
```
Then c9195d72e231a98cf42aa9d5226cd136ce62ba2d changed how this worked where the seed was `None`. In `__init__()` the value of `self.random` was set to a global `mimesis.random.random` instance and a `.reseed()` method was added that is only called from `__init__()` when the seed is not `None`. Subsequent manual …

Fixed providers to use isolated `random` instance with seed of `None`.

---

CONTRIBUTORS.rst
mimesis/providers/date.py
tests/test_providers/test_datetime.py

Hi,
we were evaluating our [automated unit test generator](https://github.com/se2p/pynguin) on mimesis and found a bug in `Datetime.bulk_create_datetimes`. It is possible to call this method without `**kwargs` or with `**kwargs` that represent a non-positive timedelta. In such a case, the `while` loop in this method never terminates. I have added a simple check to verify that the used timedelta is positive and also added a test case for it.
Best regards
Florian

Avoid infinite loop in `Datetime.bulk_create_datetimes` by checking for positive timedelta

---

mimesis/providers/choice.py

The random selection in `mimesis.providers.choice.Choice.__call__` can be very slow for certain inputs.
For example, calling it with `(items="a" * 10000000 + "b", unique=True, length=2)` will cause the while loop to run extremely long, because it needs to sample two unique elements, but will sample 'a' many times. I have changed the code to use the faster implementations in the underlying random class, i.e., `sample` and `choices`.
For the above example, the old implementation took 8 seconds on my machine to compute, whereas the new implementation takes 0.23s.
I know that this input is probably not realistic, but I wanted to fix it nonetheless 😅 
I did not add further test cases, as the functionality is unchanged, but the existing tests still pass and the implementation should be faster …

Improve random sampling performance.

---

mimesis/data/sv/person.json

Fixes #1424
Also fixed some spelling errors.
https://svenska.se/tre/?sok=kompromissvillig&pz=1
https://svenska.se/tre/?sok=kommunist&pz=1

Fix spelling. Remove description from name entry

---

pyproject.toml

Now it will be detected :)
As the next step, I propose to move tests from `pytest-mimesis`.

Add `pytest` entry in `pyproject.toml`

---

CHANGELOG.rst
tests/test_schema.py

- [] I have created at least one test case for the changes I have made
Closes #1517

Modify tests to pass in Windows

---

mimesis/datasets/int/path.py
mimesis/providers/path.py

sys.platform includes the version number e.g. freebsd13
Treat all FreeBSD versions as a single platform
- I did not add new tests, but I did run the test suite on FreeBSD.
- Before: `KeyError: 'freebsd13'` in `mimesis/providers/path.py:37 in __init__:`
- After: `6149 passed in 13.25s`
Closes #1544

Support FreeBSD
